FROM rocker/verse:4.0.3

LABEL org.label-schema.license="GPL-2.0" \
      org.label-schema.vcs-url="https://github.com/geiser/docker/r-dev" \
      org.label-schema.vendor="Geiser Projects" \
      maintainer="Geiser Chalco <geiser@alumni@usp.br>"

